// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2024 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

use std::sync::Arc;

use prometheus::{
    Histogram, HistogramVec, IntCounter, IntCounterVec, IntGauge, IntGaugeVec, Registry,
    exponential_buckets, register_histogram_vec_with_registry, register_histogram_with_registry,
    register_int_counter_vec_with_registry, register_int_counter_with_registry,
    register_int_gauge_vec_with_registry, register_int_gauge_with_registry,
};

use crate::network::metrics::NetworkMetrics;

// starts from 1μs, 50μs, 100μs...
const FINE_GRAINED_LATENCY_SEC_BUCKETS: &[f64] = &[
    0.000_001, 0.000_050, 0.000_100, 0.000_500, 0.001, 0.005, 0.01, 0.05, 0.1, 0.15, 0.2, 0.25,
    0.3, 0.35, 0.4, 0.45, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.5, 3.0, 3.5,
    4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 10., 20., 30., 60., 120.,
];

const NUM_BUCKETS: &[f64] = &[
    1.0,
    2.0,
    4.0,
    8.0,
    10.0,
    20.0,
    40.0,
    80.0,
    100.0,
    150.0,
    200.0,
    400.0,
    800.0,
    1000.0,
    2000.0,
    3000.0,
    5000.0,
    10000.0,
    20000.0,
    30000.0,
    50000.0,
    100_000.0,
    200_000.0,
    300_000.0,
    500_000.0,
    1_000_000.0,
];

const LATENCY_SEC_BUCKETS: &[f64] = &[
    0.001, 0.005, 0.01, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.6, 0.7, 0.8, 0.9,
    1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5,
    9.0, 9.5, 10., 12.5, 15., 17.5, 20., 25., 30., 60., 90., 120., 180., 300.,
];

const SIZE_BUCKETS: &[f64] = &[
    100.,
    400.,
    800.,
    1_000.,
    2_000.,
    5_000.,
    10_000.,
    20_000.,
    50_000.,
    100_000.,
    200_000.0,
    300_000.0,
    400_000.0,
    500_000.0,
    1_000_000.0,
    2_000_000.0,
    3_000_000.0,
    5_000_000.0,
    10_000_000.0,
]; // size in bytes

pub(crate) struct Metrics {
    pub(crate) node_metrics: NodeMetrics,
    pub(crate) network_metrics: NetworkMetrics,
}

pub(crate) fn initialise_metrics(registry: Registry) -> Arc<Metrics> {
    let node_metrics = NodeMetrics::new(&registry);
    let network_metrics = NetworkMetrics::new(&registry);

    Arc::new(Metrics {
        node_metrics,
        network_metrics,
    })
}

#[cfg(test)]
pub(crate) fn test_metrics() -> Arc<Metrics> {
    initialise_metrics(Registry::new())
}

pub(crate) struct NodeMetrics {
    pub(crate) delay_in_sending_blocks: Histogram,
    pub(crate) block_header_commit_latency: Histogram,
    pub(crate) proposed_blocks: IntCounterVec,
    pub(crate) proposed_block_header_size: Histogram,
    pub(crate) proposed_block_size: Histogram,
    pub(crate) proposed_block_transactions: Histogram,
    pub(crate) proposed_block_ancestors: Histogram,
    pub(crate) proposed_block_ancestors_depth: HistogramVec,
    pub(crate) proposed_block_ancestors_timestamp_drift_ms: IntCounterVec,
    pub(crate) proposed_block_acknowledgments: Histogram,
    pub(crate) proposed_block_acknowledgments_depth: HistogramVec,
    pub(crate) gap_to_available_commit: IntGauge,
    pub(crate) gap_to_unavailable_transactions: IntGauge,
    pub(crate) highest_verified_authority_round: IntGaugeVec,
    pub(crate) lowest_verified_authority_round: IntGaugeVec,
    pub(crate) block_proposal_interval: Histogram,
    pub(crate) block_proposal_leader_wait_ms: IntCounterVec,
    pub(crate) block_proposal_leader_wait_count: IntCounterVec,
    pub(crate) block_timestamp_drift_ms: IntCounterVec,
    pub(crate) latency_to_process_stream: HistogramVec,
    pub(crate) blocks_per_commit_count: HistogramVec,
    pub(crate) core_add_blocks_batch_size: Histogram,
    pub(crate) core_add_block_headers_batch_size: Histogram,
    pub(crate) core_lock_dequeued: IntCounter,
    pub(crate) reconstruction_jobs_started: IntCounter,
    pub(crate) reconstruction_jobs_finished: IntCounter,
    pub(crate) accepted_transactions_source: IntCounterVec,
    pub(crate) accepted_transactions_round_gap: HistogramVec,
    pub(crate) shard_accumulators: IntGauge,
    pub(crate) reconstruction_lag: Histogram,
    pub(crate) reconstructed_transactions_unknown: IntGauge,
    pub(crate) reconstruction_queue: IntGauge,
    pub(crate) shard_reconstructor_processed_transactions: IntGauge,
    pub(crate) core_lock_enqueued: IntCounter,
    pub(crate) core_skipped_proposals: IntCounterVec,
    pub(crate) highest_accepted_authority_round: IntGaugeVec,
    pub(crate) highest_accepted_round: IntGauge,
    pub(crate) accepted_block_header_time_drift_ms: IntCounterVec,
    pub(crate) accepted_block_headers: IntCounterVec,
    pub(crate) accepted_block_headers_source: IntCounterVec,
    pub(crate) accepted_block_headers_round_gap: HistogramVec,
    pub(crate) core_skipped_headers: IntCounterVec,
    pub(crate) core_skipped_transactions: IntCounterVec,
    pub(crate) cordial_knowledge_useful_headers_authors: IntCounterVec,
    pub(crate) cordial_knowledge_useful_shards_authors: IntCounterVec,
    pub(crate) dag_state_recent_transactions: IntGauge,
    pub(crate) dag_state_recent_headers: IntGauge,
    pub(crate) dag_state_recent_shards: IntGauge,
    pub(crate) dag_state_recent_refs: IntGauge,
    pub(crate) dag_state_pending_commit_votes: IntGauge,
    pub(crate) dag_state_pending_acknowledgments: IntGauge,
    pub(crate) cordial_knowledge_message_batch_size: Histogram,
    pub(crate) cordial_knowledge_processed_messages: IntCounterVec,
    pub(crate) cordial_knowledge_entries: IntGauge,
    pub(crate) cordial_knowledge_headers_not_known: IntGauge,
    pub(crate) cordial_knowledge_shards_not_known: IntGauge,
    pub(crate) dag_state_store_read_count: IntCounterVec,
    pub(crate) dag_state_store_write_count: IntCounter,
    pub(crate) synchronizer_fetch_block_headers_scheduler_inflight: IntGauge,
    pub(crate) synchronizer_fetch_block_headers_scheduler_skipped: IntCounterVec,
    pub(crate) synchronizer_fetched_block_headers_by_peer: IntCounterVec,
    pub(crate) synchronizer_skipped_block_headers_by_peer: IntCounterVec,
    pub(crate) synchronizer_requested_block_headers_by_peer: IntCounterVec,
    pub(crate) synchronizer_missing_block_headers_by_authority: IntCounterVec,
    pub(crate) synchronizer_current_missing_block_headers_by_authority: IntGaugeVec,
    pub(crate) synchronizer_fetched_block_headers_by_authority: IntCounterVec,
    pub(crate) synchronizer_requested_block_headers_by_authority: IntCounterVec,
    pub(crate) synchronizer_fetch_failures_by_peer: IntCounterVec,
    pub(crate) synchronizer_process_fetched_failures_by_peer: IntCounterVec,
    pub(crate) synchronizer_invalid_block_headers: IntCounterVec,
    pub(crate) bundles_with_invalid_parts: IntCounterVec,
    pub(crate) invalid_transactions: IntCounterVec,
    pub(crate) valid_headers_in_bundles: IntCounterVec,
    pub(crate) filtered_headers_in_bundles: IntCounterVec,
    pub(crate) received_unique_headers_from_bundles: IntCounterVec,
    pub(crate) processed_duplicated_headers_in_bundles: IntCounterVec,
    pub(crate) valid_shards_in_bundles: IntCounterVec,
    pub(crate) missing_ancestors_from_streaming: HistogramVec,
    pub(crate) missing_ancestors_from_streaming_round_gap: Histogram,
    pub(crate) additional_headers_round_gap: Histogram,
    pub(crate) rejected_blocks: IntCounterVec,
    pub(crate) skipped_empty_transaction_acknowledgments: IntCounterVec,
    pub(crate) subscribed_block_bundles: IntCounterVec,
    pub(crate) verified_blocks: IntCounterVec,
    pub(crate) decided_leaders_total: IntCounterVec,
    pub(crate) last_committed_authority_round: IntGaugeVec,
    pub(crate) last_committed_leader_round: IntGauge,
    pub(crate) last_commit_index: IntGauge,
    pub(crate) last_commit_time_diff: Histogram,
    pub(crate) last_known_own_block_header_round: IntGauge,
    pub(crate) sync_last_known_own_block_header_retries: IntCounter,
    pub(crate) commit_round_advancement_interval: Histogram,
    pub(crate) last_decided_leader_round: IntGauge,
    pub(crate) missing_block_headers_total: IntCounter,
    pub(crate) missing_block_headers_after_fetch_total: IntCounter,
    pub(crate) num_of_bad_nodes: IntGauge,
    pub(crate) quorum_receive_latency: Histogram,
    pub(crate) transactions_per_commit_count: HistogramVec,
    pub(crate) non_empty_blocks_per_commit_count: HistogramVec,
    pub(crate) committed_non_empty_blocks_per_authority: IntCounterVec,
    pub(crate) transactions_synchronizer_fetched_transactions_by_peer: IntCounterVec,
    pub(crate) transactions_synchronizer_fetched_transactions_by_authority: IntCounterVec,
    pub(crate) transactions_synchronizer_missing_transactions_by_authority: IntCounterVec,
    pub(crate) transactions_synchronizer_current_missing_transactions_by_authority: IntGaugeVec,
    pub(crate) transactions_synchronizer_periodic_inflight: IntGauge,
    pub(crate) transactions_synchronizer_fetch_latency: HistogramVec,
    pub(crate) transactions_synchronizer_success_by_peer: IntCounterVec,
    pub(crate) transactions_synchronizer_failure_by_peer: IntCounterVec,
    pub(crate) transactions_synchronizer_inflight_requests: IntGauge,
    pub(crate) reputation_scores: IntGaugeVec,
    pub(crate) scope_processing_time: HistogramVec,
    pub(crate) sub_dags_per_commit_count: HistogramVec,
    pub(crate) transaction_commit_latency: Histogram,
    pub(crate) block_headers_suspensions: IntCounterVec,
    pub(crate) block_header_unsuspensions: IntCounterVec,
    pub(crate) suspended_block_header_time: HistogramVec,
    pub(crate) block_manager_suspended_block_headers: IntGauge,
    pub(crate) block_manager_suspended_blocks: IntGauge,
    pub(crate) block_manager_missing_ancestors: IntGauge,
    pub(crate) block_manager_missing_block_headers: IntGauge,
    pub(crate) block_manager_missing_block_headers_by_authority: IntCounterVec,
    pub(crate) block_manager_missing_ancestors_by_authority: IntCounterVec,
    pub(crate) block_manager_gc_floor: IntGauge,
    pub(crate) block_manager_gc_evicted_missing_ancestors_total: IntCounter,
    pub(crate) block_manager_gc_evicted_fetch_entries_total: IntCounter,
    pub(crate) block_manager_gc_unsuspended_total: IntCounter,
    pub(crate) block_manager_gc_evicted_suspended_transactions_total: IntCounter,
    pub(crate) block_manager_gc_evicted_old_headers_total: IntCounter,
    pub(crate) threshold_clock_round: IntGauge,
    pub(crate) subscriber_connection_attempts: IntCounterVec,
    pub(crate) subscribed_to: IntGaugeVec,
    pub(crate) subscribed_by: IntGaugeVec,
    pub(crate) commit_sync_inflight_fetches: IntGaugeVec,
    pub(crate) commit_sync_pending_fetches: IntGaugeVec,
    pub(crate) commit_sync_fetch_commits_handler_uncertified_skipped: IntCounterVec,
    pub(crate) commit_sync_fetched_commits: IntCounterVec,
    pub(crate) commit_sync_fetched_block_headers: IntCounter,
    pub(crate) commit_sync_total_fetched_block_headers_size: IntCounter,
    pub(crate) commit_sync_total_fetched_transactions_size: IntCounterVec,
    pub(crate) commit_sync_quorum_index: IntGauge,
    pub(crate) commit_sync_highest_synced_index: IntGaugeVec,
    pub(crate) commit_sync_highest_fetched_index: IntGaugeVec,
    pub(crate) commit_sync_local_index: IntGauge,
    pub(crate) commit_sync_gap_on_processing: IntCounterVec,
    pub(crate) commit_sync_fetch_loop_latency: Histogram,
    pub(crate) commit_sync_fetch_once_latency: HistogramVec,
    pub(crate) commit_sync_fetch_once_errors: IntCounterVec,
    pub(crate) commit_sync_fetch_missing_block_headers: IntCounterVec,
    pub(crate) commit_sync_fetch_missing_transactions: IntCounterVec,
    pub(crate) commit_sync_voting_block_headers_hits: IntCounter,
    pub(crate) commit_sync_voting_block_headers_fallbacks: IntCounter,
    pub(crate) syncer_paused_by_fast_sync: IntCounterVec,
    pub(crate) uptime: Histogram,
}

impl NodeMetrics {
    pub(crate) fn new(registry: &Registry) -> Self {
        Self {
            delay_in_sending_blocks: register_histogram_with_registry!(
                "delay_in_sending_blocks",
                "The time taken between block creation and block sending.",
                LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            block_header_commit_latency: register_histogram_with_registry!(
                "block_header_commit_latency",
                "The time taken between block creation and commit of block header.",
                LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            transaction_commit_latency: register_histogram_with_registry!(
                "transaction_commit_latency",
                "The time taken between inclusion transactions in a block and transactions are sequenced.",
                LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            proposed_blocks: register_int_counter_vec_with_registry!(
                "proposed_blocks",
                "Total number of proposed blocks. The reason gives a hint what triggered block creation",
                &["reason"],
                registry,
            ).unwrap(),
            proposed_block_header_size: register_histogram_with_registry!(
                "proposed_block_header_size",
                "The size (in bytes) of proposed block headers",
                SIZE_BUCKETS.to_vec(),
                registry
            ).unwrap(),
            proposed_block_size: register_histogram_with_registry!(
                "proposed_block_size",
                "The size (in bytes) of proposed blocks",
                SIZE_BUCKETS.to_vec(),
                registry
            ).unwrap(),
            proposed_block_transactions: register_histogram_with_registry!(
                "proposed_block_transactions",
                "# of transactions contained in proposed blocks",
                NUM_BUCKETS.to_vec(),
                registry
            ).unwrap(),
            proposed_block_ancestors: register_histogram_with_registry!(
                "proposed_block_ancestors",
                "Number of ancestors in proposed blocks",
                exponential_buckets(1.0, 1.4, 20).unwrap(),
                registry,
            ).unwrap(),
            proposed_block_ancestors_depth: register_histogram_vec_with_registry!(
                "proposed_block_ancestors_depth",
                "The depth in rounds of ancestors included in newly proposed blocks",
                &["authority"],
                exponential_buckets(1.0, 2.0, 14).unwrap(),
                registry,
            ).unwrap(),
            proposed_block_ancestors_timestamp_drift_ms: register_int_counter_vec_with_registry!(
                "proposed_block_ancestors_timestamp_drift_ms",
                "The drift in ms of ancestors' timestamps included in newly proposed blocks",
                &["authority"],
                registry,
            ).unwrap(),
            proposed_block_acknowledgments: register_histogram_with_registry!(
                "proposed_block_acknowledgments",
                "Number of acknowledgments in proposed blocks",
                exponential_buckets(1.0, 1.4, 20).unwrap(),
                registry,
            ).unwrap(),
            proposed_block_acknowledgments_depth: register_histogram_vec_with_registry!(
                "proposed_block_acknowledgments_depth",
                "The depth in rounds of acknowledgments included in newly proposed blocks",
                &["authority"],
                exponential_buckets(1.0, 2.0, 14).unwrap(),
                registry,
            ).unwrap(),
            latency_to_process_stream: register_histogram_vec_with_registry!(
                "latency_to_process_stream",
                "The latency between block creation and processing stream from peer",
                &["peer"],
                exponential_buckets(0.002, 1.5, 18).unwrap(),
                registry,
            ).unwrap(),
            highest_verified_authority_round: register_int_gauge_vec_with_registry!(
                "highest_verified_authority_round",
                "The highest round of received verified block for the corresponding authority",
                &["authority"],
                registry,
            ).unwrap(),
            lowest_verified_authority_round: register_int_gauge_vec_with_registry!(
                "lowest_verified_authority_round",
                "The lowest round of received verified block for the corresponding authority",
                &["authority"],
                registry,
            ).unwrap(),
            block_proposal_interval: register_histogram_with_registry!(
                "block_proposal_interval",
                "Intervals (in secs) between block proposals.",
                FINE_GRAINED_LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            block_proposal_leader_wait_ms: register_int_counter_vec_with_registry!(
                "block_proposal_leader_wait_ms",
                "Total time in ms spent waiting for a leader when proposing blocks.",
                &["authority"],
                registry,
            ).unwrap(),
            block_proposal_leader_wait_count: register_int_counter_vec_with_registry!(
                "block_proposal_leader_wait_count",
                "Total times waiting for a leader when proposing blocks.",
                &["authority"],
                registry,
            ).unwrap(),
            block_timestamp_drift_ms: register_int_counter_vec_with_registry!(
                "block_timestamp_drift_ms",
                "The clock drift time between a received block and the current node's time.",
                &["authority", "source"],
                registry,
            ).unwrap(),
            blocks_per_commit_count: register_histogram_vec_with_registry!(
                "blocks_per_commit_count",
                "The number of blocks per commit.",
                &["source"],
                NUM_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            reconstruction_lag: register_histogram_with_registry!(
                "reconstruction_lag",
                "The number of rounds between current round and reconstructed transactions.",
                NUM_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            core_add_blocks_batch_size: register_histogram_with_registry!(
                "core_add_blocks_batch_size",
                "The number of blocks received from Core for processing on a single batch",
                NUM_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            core_add_block_headers_batch_size: register_histogram_with_registry!(
                "core_add_block_headers_batch_size",
                "The number of block headers received from Core for processing on a single batch",
                NUM_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            gap_to_available_commit: register_int_gauge_with_registry!(
                "gap_to_available_commit",
                "Gap in rounds between last pending commit and last available commit",
                registry,
            ).unwrap(),
            gap_to_unavailable_transactions: register_int_gauge_with_registry!(
                "gap_to_unavailable_transactions",
                "Gap in rounds between current round and the oldest unavailable transaction",
                registry,
            ).unwrap(),
            reconstruction_jobs_started: register_int_counter_with_registry!(
                "reconstruction_jobs_started",
                "Number of reconstruction jobs spawned",
                registry,
            ).unwrap(),
            reconstruction_jobs_finished: register_int_counter_with_registry!(
                "reconstruction_jobs_finished",
                "Number of reconstruction jobs finished",
                registry,
            ).unwrap(),
            accepted_transactions_source: register_int_counter_vec_with_registry!(
                "accepted_transactions_source",
                "Number of accepted transactions by source and authority",
                &["source", "authority"],
                registry,
            ).unwrap(),
            accepted_transactions_round_gap: register_histogram_vec_with_registry!(
                "accepted_transactions_round_gap",
                "Round gap of accepted transactions to clock round",
                &["source"],
                vec![0.0, 1.0, 2.0, 5.0, 10.0, 20.0, 40.0, 80.0, 100.0, 200.0, 400.0, 800.0, 1000.0],
                registry,
            ).unwrap(),
            core_lock_dequeued: register_int_counter_with_registry!(
                "core_lock_dequeued",
                "Number of dequeued core requests",
                registry,
            ).unwrap(),
            core_lock_enqueued: register_int_counter_with_registry!(
                "core_lock_enqueued",
                "Number of enqueued core requests",
                registry,
            ).unwrap(),
            core_skipped_proposals: register_int_counter_vec_with_registry!(
                "core_skipped_proposals",
                "Number of proposals skipped in the Core, per reason",
                &["reason"],
                registry,
            ).unwrap(),
            highest_accepted_authority_round: register_int_gauge_vec_with_registry!(
                "highest_accepted_authority_round",
                "The highest round where a block header has been accepted per authority. Resets on restart.",
                &["authority"],
                registry,
            ).unwrap(),
            highest_accepted_round: register_int_gauge_with_registry!(
                "highest_accepted_round",
                "The highest round where a block header has been accepted. Resets on restart.",
                registry,
            ).unwrap(),
            accepted_block_header_time_drift_ms: register_int_counter_vec_with_registry!(
                "accepted_block_header_time_drift_ms",
                "The time drift in ms of an accepted block header compared to local time",
                &["authority"],
                registry,
            ).unwrap(),
            accepted_block_headers: register_int_counter_vec_with_registry!(
                "accepted_block_headers",
                "Number of accepted block headers by source (own, others)",
                &["source"],
                registry,
            ).unwrap(),
            accepted_block_headers_source: register_int_counter_vec_with_registry!(
                "accepted_block_headers_source",
                "Number of accepted block headers by source and authority",
                &["source", "authority"],
                registry,
            ).unwrap(),
            accepted_block_headers_round_gap: register_histogram_vec_with_registry!(
                "accepted_block_headers_round_gap",
                "Round gap of accepted block headers to clock round",
                &["source"],
                vec![0.0, 1.0, 2.0, 5.0, 10.0, 20.0, 40.0, 80.0, 100.0, 200.0, 400.0, 800.0, 1000.0],
                registry,
            ).unwrap(),
            core_skipped_headers: register_int_counter_vec_with_registry!(
                "core_skipped_headers",
                "Number of block headers skipped in core because already in DAG or suspended",
                &["authority", "source"],
                registry,
            ).unwrap(),
            core_skipped_transactions: register_int_counter_vec_with_registry!(
                "core_skipped_transactions",
                "Number of non-empty transactions skipped in core because already in DAG",
                &["authority", "source"],
                registry,
            ).unwrap(),
            shard_accumulators: register_int_gauge_with_registry!(
                "shard_accumulators",
                "The number of shard accumulators currently in memory",
                registry,
            ).unwrap(),
            reconstruction_queue: register_int_gauge_with_registry!(
                "reconstruction_queue",
                "The current number of pending reconstruction jobs in the queue",
                registry,
            ).unwrap(),
            shard_reconstructor_processed_transactions: register_int_gauge_with_registry!(
                "shard_reconstructor_processed_transactions",
                "Number of processed transactions tracked to prevent duplicate reconstruction",
                registry,
            ).unwrap(),
            reconstructed_transactions_unknown: register_int_gauge_with_registry!(
            "reconstructed_transactions_unknown",
            "The current number of reconstructed transactions which are unknown to dag state",
            registry,
            ).unwrap(),
            dag_state_recent_transactions: register_int_gauge_with_registry!(
                "dag_state_recent_transactions",
                "Number of recent transactions cached in the DagState",
                registry,
            ).unwrap(),
            dag_state_recent_headers: register_int_gauge_with_registry!(
                "dag_state_recent_headers",
                "Number of recent block headers cached in the DagState",
                registry,
            ).unwrap(),
            dag_state_recent_shards: register_int_gauge_with_registry!(
                "dag_state_recent_shards",
                "Number of recent shards cached in the DagState",
                registry,
            ).unwrap(),
            dag_state_recent_refs: register_int_gauge_with_registry!(
                "dag_state_recent_refs",
                "Number of recent refs cached in the DagState",
                registry,
            ).unwrap(),
            dag_state_pending_commit_votes: register_int_gauge_with_registry!(
                "dag_state_pending_commit_votes",
                "Number of pending commit votes in the DagState",
                registry,
            ).unwrap(),
            dag_state_pending_acknowledgments: register_int_gauge_with_registry!(
                "dag_state_pending_acknowledgments",
                "Number of pending acknowledgments in the DagState",
                registry,
            ).unwrap(),
            cordial_knowledge_message_batch_size: register_histogram_with_registry!(
                "cordial_knowledge_message_batch_size",
                "Size of the batch of messages sent to connections in cordial knowledge",
                vec![0.0, 1.0, 2.0, 5.0, 10.0, 20.0, 40.0, 80.0, 100.0, 200.0, 400.0, 800.0, 1000.0],
                registry,
            ).unwrap(),
            cordial_knowledge_processed_messages: register_int_counter_vec_with_registry!(
                "cordial_knowledge_processed_messages",
                "Number of Cordial Knowledge messages processed",
                &["type"],
                registry,
            ).unwrap(),
            cordial_knowledge_entries: register_int_gauge_with_registry!(
                "cordial_knowledge_entries",
                "Total entries in the global cordial knowledge map",
                registry,
            ).unwrap(),
            cordial_knowledge_headers_not_known: register_int_gauge_with_registry!(
                "cordial_knowledge_headers_not_known",
                "Total unknown header entries across all connection knowledges",
                registry,
            ).unwrap(),
            cordial_knowledge_shards_not_known: register_int_gauge_with_registry!(
                "cordial_knowledge_shards_not_known",
                "Total unknown shard entries across all connection knowledges",
                registry,
            ).unwrap(),
            dag_state_store_read_count: register_int_counter_vec_with_registry!(
                "dag_state_store_read_count",
                "Number of times DagState needs to read from store per operation type",
                &["type"],
                registry,
            ).unwrap(),
            dag_state_store_write_count: register_int_counter_with_registry!(
                "dag_state_store_write_count",
                "Number of times DagState needs to write to store",
                registry,
            ).unwrap(),
            synchronizer_fetch_block_headers_scheduler_inflight: register_int_gauge_with_registry!(
                "synchronizer_fetch_block_headers_scheduler_inflight",
                "Designates whether the synchronizer scheduler task to fetch block headers is currently running",
                registry,
            ).unwrap(),
            synchronizer_fetch_block_headers_scheduler_skipped: register_int_counter_vec_with_registry!(
                "synchronizer_fetch_block_headers_scheduler_skipped",
                "Number of times the scheduler skipped fetching block headers",
                &["reason"],
                registry
            ).unwrap(),
            synchronizer_fetched_block_headers_by_peer: register_int_counter_vec_with_registry!(
                "synchronizer_fetched_block_headers_by_peer",
                "Number of fetched block headers per peer authority via the synchronizer and also by block authority",
                &["peer", "type"],
                registry,
            ).unwrap(),
            synchronizer_skipped_block_headers_by_peer: register_int_counter_vec_with_registry!(
                "synchronizer_skipped_block_headers_by_peer",
                "Number of skipped block headers per peer due to already being verified, by sync method",
                &["peer", "method"],
                registry,
            ).unwrap(),
            cordial_knowledge_useful_headers_authors: register_int_counter_vec_with_registry!(
                "cordial_knowledge_useful_headers_authors",
                "Useful authors for pushing headers to the local node",
                &["peer", "author"],
                registry,
            ).unwrap(),
            cordial_knowledge_useful_shards_authors: register_int_counter_vec_with_registry!(
                "cordial_knowledge_useful_shards_authors",
                "Useful authors for pushing shards to the local node",
                &["author"],
                registry,
            ).unwrap(),
            synchronizer_requested_block_headers_by_peer: register_int_counter_vec_with_registry!(
                "synchronizer_requested_block_headers_by_peer",
                "Number of requested block headers per peer authority via the synchronizer and also by block authority",
                &["peer", "type"],
                registry,
            ).unwrap(),
            synchronizer_missing_block_headers_by_authority: register_int_counter_vec_with_registry!(
                "synchronizer_missing_block_headers_by_authority",
                "Number of missing block headers per block author, as observed by the synchronizer during periodic sync.",
                &["authority"],
                registry,
            ).unwrap(),
            synchronizer_current_missing_block_headers_by_authority: register_int_gauge_vec_with_registry!(
                "synchronizer_current_missing_block_headers_by_authority",
                "Current number of missing block headers per block author, as observed by the synchronizer during periodic sync.",
                &["authority"],
                registry,
            ).unwrap(),
            synchronizer_fetch_failures_by_peer: register_int_counter_vec_with_registry!(
                "synchronizer_fetch_failures",
                "Number of fetch failures against each peer",
                &["peer", "type"],
                registry,
            ).unwrap(),
            synchronizer_process_fetched_failures_by_peer: register_int_counter_vec_with_registry!(
                "synchronizer_process_fetched_failures",
                "Number of failures for processing fetched blocks against each peer",
                &["peer", "type"],
                registry,
            ).unwrap(),
            synchronizer_invalid_block_headers: register_int_counter_vec_with_registry!(
                "synchronizer_invalid_block_headers",
                "Number of invalid headers received from each peer",
                &["peer", "source", "error"],
                registry,
            ).unwrap(),
            synchronizer_fetched_block_headers_by_authority: register_int_counter_vec_with_registry!(
                "synchronizer_fetched_block_headers_by_authority",
                "Number of fetched block headers per block author via the synchronizer",
                &["authority", "type"],
                registry,
            ).unwrap(),
            synchronizer_requested_block_headers_by_authority: register_int_counter_vec_with_registry!(
                "synchronizer_requested_block_headers_by_authority",
                "Number of requested block headers per block author via the synchronizer",
                &["authority", "type"],
                registry,
            ).unwrap(),
            last_known_own_block_header_round: register_int_gauge_with_registry!(
                "last_known_own_block_header_round",
                "The highest round of our own block header that has been synced from peers during an amnesia recovery",
                registry,
            ).unwrap(),
            sync_last_known_own_block_header_retries: register_int_counter_with_registry!(
                "sync_last_known_own_block_header_retries",
                "Number of times this node tried to fetch the last own block header from peers",
                registry,
            ).unwrap(),
            transactions_per_commit_count: register_histogram_vec_with_registry!(
                "transactions_per_commit_count",
                "The number of transactions per commit.",
                &["source"],
                NUM_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            non_empty_blocks_per_commit_count: register_histogram_vec_with_registry!(
                "non_empty_blocks_per_commit_count",
                "The number of non-empty blocks per commit.",
                &["source"],
                NUM_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            committed_non_empty_blocks_per_authority: register_int_counter_vec_with_registry!(
                "committed_non_empty_blocks_per_authority",
                "Number of blocks committed with transactions per block author",
                &["authority"],
                registry,
            ).unwrap(),
            bundles_with_invalid_parts: register_int_counter_vec_with_registry!(
                "bundles_with_invalid_parts",
                "Number of bundles that contain invalid parts per peer",
                &["authority", "invalid_part", "error"],
                registry,
            ).unwrap(),
            valid_headers_in_bundles: register_int_counter_vec_with_registry!(
                "valid_headers_in_bundles",
                "Number of valid block headers received from block bundles per sender",
                &["authority", "source"],
                registry,
            ).unwrap(),
            filtered_headers_in_bundles: register_int_counter_vec_with_registry!(
                "filtered_headers_in_bundles",
                "Number of filtered block headers received from block bundles per sender authority",
                &["authority", "source"],
                registry,
            ).unwrap(),
            received_unique_headers_from_bundles: register_int_counter_vec_with_registry!(
                "received_unique_headers_from_a_bundle",
                "Number of unique block headers received from block bundles per sender authority",
                &["authority", "source"],
                registry,
            ).unwrap(),
            processed_duplicated_headers_in_bundles: register_int_counter_vec_with_registry!(
                "processed_duplicated_headers_in_bundles",
                "Number of times block headers from bundles were not filtered and processed extra time (i.e. deserialized and verified) per sender authority",
                &["authority", "source"],
                registry,
            ).unwrap(),
            valid_shards_in_bundles: register_int_counter_vec_with_registry!(
                "valid_shards_in_bundles",
                "Number of valid shards received from block bundles per sender authority",
                &["authority", "source"],
                registry,
            ).unwrap(),
            missing_ancestors_from_streaming: register_histogram_vec_with_registry!(
                "missing_ancestors_from_streaming",
                "Number of missing ancestors of blocks and headers received through streaming",
                &["source"],
                registry,
            ).unwrap(),
            missing_ancestors_from_streaming_round_gap: register_histogram_with_registry!(
                "missing_ancestors_from_streaming_round_gap",
                "Round gap to missing ancestors of blocks and headers received through streaming",
                vec![0.0, 1.0, 2.0, 5.0, 10.0, 20.0, 40.0, 80.0, 100.0, 200.0, 400.0, 800.0, 1000.0],
                registry,
            ).unwrap(),
            additional_headers_round_gap: register_histogram_with_registry!(
                "additional_headers_round_gap",
                "Round gap between additional block headers in bundles and the main block",
                vec![0.0, 1.0, 2.0, 5.0, 10.0, 20.0, 40.0, 80.0, 100.0, 200.0, 400.0, 800.0, 1000.0],
                registry,
            ).unwrap(),
            rejected_blocks: register_int_counter_vec_with_registry!(
                "rejected_blocks",
                "Number of blocks rejected because last commit index is lagging quorum commit index too much",
                &["reason"],
                registry,
            ).unwrap(),
            skipped_empty_transaction_acknowledgments: register_int_counter_vec_with_registry!(
                "skipped_empty_transaction_acknowledgments",
                "Number of transaction acknowledgments skipped due to empty transaction vector in VerifiedTransaction",
                &["authority"],
                registry,
            ).unwrap(),
            subscribed_block_bundles: register_int_counter_vec_with_registry!(
                "subscribed_block_bundles",
                "Number of block bundles received from each peer through streaming before verification",
                &["authority"],
                registry,
            ).unwrap(),
            verified_blocks: register_int_counter_vec_with_registry!(
                "verified_blocks",
                "Number of blocks received from each peer that are verified",
                &["authority"],
                registry,
            ).unwrap(),
            decided_leaders_total: register_int_counter_vec_with_registry!(
                "decided_leaders_total",
                "Total number of (direct or indirect, skip or commit) decided leaders per authority",
                &["authority", "commit_type"],
                registry,
            ).unwrap(),
            last_committed_authority_round: register_int_gauge_vec_with_registry!(
                "last_committed_authority_round",
                "The last round committed by authority.",
                &["authority"],
                registry,
            ).unwrap(),
            last_committed_leader_round: register_int_gauge_with_registry!(
                "last_committed_leader_round",
                "The last round where a leader was committed to store and sent to commit consumer.",
                registry,
            ).unwrap(),
            last_commit_index: register_int_gauge_with_registry!(
                "last_commit_index",
                "Index of the last commit.",
                registry,
            ).unwrap(),
            last_commit_time_diff: register_histogram_with_registry!(
                "last_commit_time_diff",
                "The time diff between the last commit and previous one.",
                LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            commit_round_advancement_interval: register_histogram_with_registry!(
                "commit_round_advancement_interval",
                "Intervals (in secs) between commit round advancements.",
                FINE_GRAINED_LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            last_decided_leader_round: register_int_gauge_with_registry!(
                "last_decided_leader_round",
                "The last round where a commit decision was made.",
                registry,
            ).unwrap(),
            missing_block_headers_total: register_int_counter_with_registry!(
                "missing_block_headers_total",
                "Total cumulative number of missing block headers",
                registry,
            ).unwrap(),
            missing_block_headers_after_fetch_total: register_int_counter_with_registry!(
                "missing_block_headers_after_fetch_total",
                "Total number of missing block headers after fetching from peer",
                registry,
            ).unwrap(),
            num_of_bad_nodes: register_int_gauge_with_registry!(
                "num_of_bad_nodes",
                "The number of bad nodes in the new leader schedule",
                registry
            ).unwrap(),
            quorum_receive_latency: register_histogram_with_registry!(
                "quorum_receive_latency",
                "The time it took to receive a new round quorum of blocks",
                registry
            ).unwrap(),
            invalid_transactions: register_int_counter_vec_with_registry!(
                "invalid_transactions",
                "Number of invalid transactions per peer authority",
                &["authority", "source", "error"],
                registry,
            ).unwrap(),
            transactions_synchronizer_fetched_transactions_by_peer: register_int_counter_vec_with_registry!(
                "transaction_synchronizer_fetched_transactions_by_peer",
                "Number of fetched transactions per peer authority via the transaction synchronizer",
                &["peer", "type"],
                registry,
            ).unwrap(),
            transactions_synchronizer_fetched_transactions_by_authority: register_int_counter_vec_with_registry!(
                "transaction_synchronizer_fetched_transactions_by_authority",
                "Number of fetched transactions per block author via the transaction synchronizer",
                &["authority", "type"],
                registry,
            ).unwrap(),
            transactions_synchronizer_missing_transactions_by_authority: register_int_counter_vec_with_registry!(
                "transactions_synchronizer_missing_transactions_by_authority",
                "Number of missing transactions per block author, as observed by the transaction synchronizer during periodic sync.",
                &["authority"],
                registry,
            ).unwrap(),
            transactions_synchronizer_current_missing_transactions_by_authority: register_int_gauge_vec_with_registry!(
                "transactions_synchronizer_current_missing_transactions_by_authority",
                "Current number of missing transactions per block author, as observed by the transaction synchronizer during periodic sync.",
                &["authority"],
                registry,
            ).unwrap(),
            transactions_synchronizer_periodic_inflight: register_int_gauge_with_registry!(
                "fetch_transactions_scheduler_inflight",
                "Designates whether the transaction synchronizer scheduler task to fetch transactions is currently running",
                registry,
            ).unwrap(),
            reputation_scores: register_int_gauge_vec_with_registry!(
                "reputation_scores",
                "Reputation scores for each authority",
                &["authority"],
                registry,
            ).unwrap(),
            scope_processing_time: register_histogram_vec_with_registry!(
                "scope_processing_time",
                "The processing time of a specific code scope",
                &["scope"],
                FINE_GRAINED_LATENCY_SEC_BUCKETS.to_vec(),
                registry
            ).unwrap(),
            sub_dags_per_commit_count: register_histogram_vec_with_registry!(
                "sub_dags_per_commit_count",
                "The number of subdags per commit.",
                &["source"],
                registry,
            ).unwrap(),
            block_headers_suspensions: register_int_counter_vec_with_registry!(
                "block_headers_suspensions",
                "The number block headers suspensions. The counter is reported uniquely, so if a header is sent for reprocessing while already suspended then is not double counted",
                &["authority"],
                registry,
            ).unwrap(),
            block_header_unsuspensions: register_int_counter_vec_with_registry!(
                "block_header_unsuspensions",
                "The number of block headers unsuspensions.",
                &["authority"],
                registry,
            ).unwrap(),
            suspended_block_header_time: register_histogram_vec_with_registry!(
                "suspended_block_header_time",
                "The time for which a block header remains suspended",
                &["authority"],
                registry,
            ).unwrap(),
            block_manager_suspended_block_headers: register_int_gauge_with_registry!(
                "block_manager_suspended_block_headers",
                "The number of block headers currently suspended in the block manager",
                registry,
            ).unwrap(),
            block_manager_suspended_blocks: register_int_gauge_with_registry!(
                "block_manager_suspended_blocks",
                "The number of full blocks suspended in the block manager awaiting header acceptance",
                registry,
            ).unwrap(),
            block_manager_missing_ancestors: register_int_gauge_with_registry!(
                "block_manager_missing_ancestors",
                "The number of headers that are missing or suspended in the block manager",
                registry,
            ).unwrap(),
            block_manager_missing_block_headers: register_int_gauge_with_registry!(
                "block_manager_missing_block_headers",
                "The number of block headers that are missing in the block manager and should be fetched",
                registry,
            ).unwrap(),
            block_manager_missing_block_headers_by_authority: register_int_counter_vec_with_registry!(
                "block_manager_missing_block_headers_by_authority",
                "The number of new missing block headers by block authority",
                &["authority"],
                registry,
            ).unwrap(),
            block_manager_missing_ancestors_by_authority: register_int_counter_vec_with_registry!(
                "block_manager_missing_ancestors_by_authority",
                "The number of headers that are missing or suspended in the block manager by authority",
                &["authority"],
                registry,
            ).unwrap(),
            block_manager_gc_floor: register_int_gauge_with_registry!(
                "block_manager_gc_floor",
                "The last GC round floor applied by the block manager. Suspended state at or below this round has been evicted.",
                registry,
            ).unwrap(),
            block_manager_gc_evicted_missing_ancestors_total: register_int_counter_with_registry!(
                "block_manager_gc_evicted_missing_ancestors_total",
                "Total number of missing-ancestor entries dropped by the block manager GC sweep",
                registry,
            ).unwrap(),
            block_manager_gc_evicted_fetch_entries_total: register_int_counter_with_registry!(
                "block_manager_gc_evicted_fetch_entries_total",
                "Total number of headers_to_fetch entries dropped by the block manager GC sweep",
                registry,
            ).unwrap(),
            block_manager_gc_unsuspended_total: register_int_counter_with_registry!(
                "block_manager_gc_unsuspended_total",
                "Total number of headers unsuspended by the block manager GC sweep because all their missing ancestors fell below the GC floor",
                registry,
            ).unwrap(),
            block_manager_gc_evicted_suspended_transactions_total: register_int_counter_with_registry!(
                "block_manager_gc_evicted_suspended_transactions_total",
                "Total number of suspended_transactions entries dropped by the block manager GC sweep",
                registry,
            ).unwrap(),
            block_manager_gc_evicted_old_headers_total: register_int_counter_with_registry!(
                "block_manager_gc_evicted_old_headers_total",
                "Total number of incoming block headers dropped because their round is at or below the GC floor",
                registry,
            ).unwrap(),
            threshold_clock_round: register_int_gauge_with_registry!(
                "threshold_clock_round",
                "The current threshold clock round. We only advance to a new round when a quorum of parents have been synced.",
                registry,
            ).unwrap(),
            subscriber_connection_attempts: register_int_counter_vec_with_registry!(
                "subscriber_connection_attempts",
                "The number of connection attempts per peer",
                &["authority", "status"],
                registry,
            ).unwrap(),
            subscribed_to: register_int_gauge_vec_with_registry!(
                "subscribed_to",
                "Peers that this authority subscribed to for block streams.",
                &["authority"],
                registry,
            ).unwrap(),
            subscribed_by: register_int_gauge_vec_with_registry!(
                "subscribed_by",
                "Peers subscribing for block streams from this authority.",
                &["authority"],
                registry,
            ).unwrap(),
            commit_sync_inflight_fetches: register_int_gauge_vec_with_registry!(
                "commit_sync_inflight_fetches",
                "The number of inflight fetches in commit syncer",
                &["source"],
                registry,
            ).unwrap(),
            commit_sync_pending_fetches: register_int_gauge_vec_with_registry!(
                "commit_sync_pending_fetches",
                "The number of pending fetches in commit syncer",
                &["source"],
                registry,
            ).unwrap(),
            commit_sync_fetched_commits: register_int_counter_vec_with_registry!(
                "commit_sync_fetched_commits",
                "The number of commits fetched via commit syncer",
                &["source"],
                registry,
            ).unwrap(),
            commit_sync_fetched_block_headers: register_int_counter_with_registry!(
                "commit_sync_fetched_block_headers",
                "The number of block headers fetched via commit syncer",
                registry,
            ).unwrap(),
            commit_sync_total_fetched_block_headers_size: register_int_counter_with_registry!(
                "commit_sync_total_fetched_block_headers_size",
                "The total size in bytes of block headers fetched via commit syncer",
                registry,
            ).unwrap(),
            commit_sync_total_fetched_transactions_size: register_int_counter_vec_with_registry!(
                "commit_sync_total_fetched_transactions_size",
                "The total size in bytes of transactions fetched via commit syncer",
                &["source"],
                registry,
            ).unwrap(),
            commit_sync_quorum_index: register_int_gauge_with_registry!(
                "commit_sync_quorum_index",
                "The maximum commit index voted by a quorum of authorities",
                registry,
            ).unwrap(),
            commit_sync_highest_synced_index: register_int_gauge_vec_with_registry!(
                "commit_sync_fetched_index",
                "The max commit index among local and fetched commits",
                &["source"],
                registry,
            ).unwrap(),
            commit_sync_highest_fetched_index: register_int_gauge_vec_with_registry!(
                "commit_sync_highest_fetched_index",
                "The max commit index that has been fetched via network",
                &["source"],
                registry,
            ).unwrap(),
            commit_sync_local_index: register_int_gauge_with_registry!(
                "commit_sync_local_index",
                "The local commit index",
                registry,
            ).unwrap(),
            commit_sync_gap_on_processing: register_int_counter_vec_with_registry!(
                "commit_sync_gap_on_processing",
                "Number of instances where a gap was found in fetched commit processing",
                &["source"],
                registry,
            ).unwrap(),
            commit_sync_fetch_loop_latency: register_histogram_with_registry!(
                "commit_sync_fetch_loop_latency",
                "The time taken to finish fetching commits and block headers from a given range",
                LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            commit_sync_fetch_once_latency: register_histogram_vec_with_registry!(
                "commit_sync_fetch_once_latency",
                "The time taken to fetch commits and block headers once",
                &["source"],
                LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            commit_sync_fetch_once_errors: register_int_counter_vec_with_registry!(
                "commit_sync_fetch_once_errors",
                "Number of errors when attempting to fetch commits and block headers from single authority during commit sync.",
                &["authority", "error", "source"],
                registry
            ).unwrap(),
            commit_sync_fetch_commits_handler_uncertified_skipped: register_int_counter_vec_with_registry!(
                "commit_sync_fetch_commits_handler_uncertified_skipped",
                "Number of uncertified commits that got skipped when fetching commits due to lack of votes",
                &["source"],
                registry,
            ).unwrap(),
            commit_sync_fetch_missing_block_headers: register_int_counter_vec_with_registry!(
                "commit_sync_fetch_missing_block_headers",
                "Number of ancestor block headers that are missing when processing headers via commit sync.",
                &["authority"],
                registry
            ).unwrap(),
            commit_sync_fetch_missing_transactions: register_int_counter_vec_with_registry!(
                "commit_sync_fetch_missing_transactions",
                "Number of committed transactions that are missing when processing transactions via commit sync.",
                &["authority", "source"],
                registry
            ).unwrap(),
            commit_sync_voting_block_headers_hits: register_int_counter_with_registry!(
                "commit_sync_voting_block_headers_hits",
                "Number of voting block headers served from voting storage during commit sync.",
                registry
            ).unwrap(),
            commit_sync_voting_block_headers_fallbacks: register_int_counter_with_registry!(
                "commit_sync_voting_block_headers_fallbacks",
                "Number of voting block headers served from regular storage (fallback) during commit sync.",
                registry
            ).unwrap(),
            syncer_paused_by_fast_sync: register_int_counter_vec_with_registry!(
                "syncer_paused_by_fast_sync",
                "Number of times a syncer (regular commit syncer, header synchronizer) skipped dispatching work because the fast commit syncer was active.",
                &["source"],
                registry,
            ).unwrap(),
            uptime: register_histogram_with_registry!(
                "uptime",
                "Total node uptime",
                LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            // New metrics for transaction synchronizer
            transactions_synchronizer_fetch_latency: register_histogram_vec_with_registry!(
                "transaction_synchronizer_fetch_latency",
                "The time taken to fetch transactions from a peer",
                &["peer", "type"],
                LATENCY_SEC_BUCKETS.to_vec(),
                registry,
            ).unwrap(),
            transactions_synchronizer_success_by_peer: register_int_counter_vec_with_registry!(
                "transaction_synchronizer_success_by_peer",
                "Number of successful transaction fetches per peer",
                &["peer", "type"],
                registry,
            ).unwrap(),
            transactions_synchronizer_failure_by_peer: register_int_counter_vec_with_registry!(
                "transaction_synchronizer_failure_by_peer",
                "Number of failed transaction fetches per peer",
                &["peer", "type", "error"],
                registry,
            ).unwrap(),
            transactions_synchronizer_inflight_requests: register_int_gauge_with_registry!(
                "transaction_synchronizer_concurrent_requests",
                "Number of concurrent transaction fetch requests",
                registry,
            ).unwrap(),
        }
    }
}
