#!/usr/bin/env python3
"""
IOTA Indexer Interactive Metrics Analyzer (Full-Screen Charts)

Reads the sync_metrics.csv generated by monitor_pruning.py and
generates multiple individual, full-screen interactive HTML charts
for deep-dive visualization.

Usage:
    pip install pandas plotly
    python analyze_pruning_size_impact.py --csv sync_metrics.csv
    python analyze_pruning_size_impact.py --csv run1.csv run2.csv run3.csv
"""

import argparse
import hashlib
import json
import os
from datetime import datetime, timezone

import pandas as pd
import plotly.graph_objects as go


def parse_args():
    parser = argparse.ArgumentParser(
        description="Analyze and plot IOTA Indexer pruning metrics as separate full-screen charts."
    )
    parser.add_argument(
        "--csv",
        type=str,
        nargs="+",
        default=["sync_metrics.csv"],
        help="Path(s) to one or more metrics CSV files (concatenated in order)",
    )
    parser.add_argument(
        "--smoothing",
        type=int,
        default=60,
        help="Rolling window size (in samples) for TPS smoothing (default: 60)",
    )
    return parser.parse_args()


def safe_json_load(val):
    if pd.isna(val):
        return {}
    try:
        return json.loads(val)
    except Exception:
        return {}


def get_latest_vacuum_dt(stats: dict):
    """Safely extract the latest vacuum or autovacuum datetime from table stats."""
    dates = []
    for k in ["last_vacuum", "last_autovacuum"]:
        val = stats.get(k)
        if val:
            try:
                # Parse to timezone-aware UTC datetime
                dates.append(pd.to_datetime(val, utc=True))
            except Exception:
                pass
    return max(dates) if dates else pd.NaT


def main():
    args = parse_args()

    csv_files = args.csv
    for f in csv_files:
        if not os.path.exists(f):
            print(f"Error: Could not find {f}")
            return

    print(f"Loading data from {len(csv_files)} CSV file(s)...")

    # Load and concatenate CSVs, tracking boundaries
    frames = []
    csv_boundaries = []  # (timestamp, label) for vertical lines between CSVs
    for csv_path in csv_files:
        part = pd.read_csv(csv_path)
        part["timestamp"] = pd.to_datetime(part["timestamp"])
        if frames:
            csv_boundaries.append(
                (part["timestamp"].iloc[0], os.path.splitext(os.path.basename(csv_path))[0])
            )
        frames.append(part)
    # Strip common prefix from boundary labels
    if csv_boundaries:
        labels = [label for _, label in csv_boundaries]
        common_prefix = os.path.commonprefix(labels)
        # Trim to last underscore so we don't cut mid-word
        trim = common_prefix.rfind("_") + 1 if "_" in common_prefix else len(common_prefix)
        if trim > 0:
            csv_boundaries = [(ts, label[trim:]) for ts, label in csv_boundaries]

    df = pd.concat(frames, ignore_index=True)
    df.sort_values("timestamp", inplace=True)
    df.reset_index(drop=True, inplace=True)

    # Create a timezone-aware version of the timestamp for accurate vacuum age math
    local_tz = datetime.now(timezone.utc).astimezone().tzinfo
    df["timestamp_utc"] = (
        pd.to_datetime(df["timestamp"]).dt.tz_localize(local_tz).dt.tz_convert("UTC")
    )

    # Calculate TPS (Transactions per Second)
    df["time_diff"] = df["timestamp"].diff().dt.total_seconds()
    df["tx_diff"] = df["tx_seq"].diff()
    df["tps"] = df["tx_diff"] / df["time_diff"]
    df["tps"] = df["tps"].fillna(0).clip(lower=0)
    df["tps_smoothed"] = df["tps"].rolling(window=args.smoothing, min_periods=1).mean()

    # Determine column names based on script versions
    stats_col = (
        "table_stats_json" if "table_stats_json" in df.columns else "table_stats"
    )
    if stats_col not in df.columns and "tables_json" in df.columns:
        stats_col = "tables_json"

    pruning_col = (
        "pruning_details_json"
        if "pruning_details_json" in df.columns
        else "pruning_details"
    )
    db_col = "pg_db_size_bytes" if "pg_db_size_bytes" in df.columns else "pg_db_size"
    disk_col = (
        "physical_disk_bytes" if "physical_disk_bytes" in df.columns else "disk_size"
    )

    # Parse JSON columns
    print("Parsing JSON columns...")
    df["table_stats_dict"] = df[stats_col].apply(safe_json_load)

    if pruning_col in df.columns:
        df["pruning_list"] = df[pruning_col].apply(safe_json_load)
    else:
        df["pruning_list"] = [{}] * len(df)

    # Find when WITH_PRUNING started
    pruning_start_time = None
    if "phase" in df.columns:
        pruning_phases = df[df["phase"] == "WITH_PRUNING"]
        if not pruning_phases.empty:
            pruning_start_time = pruning_phases.iloc[0]["timestamp"]

    # Extract top tables by size/bloat at the end of the run
    last_stats = df.iloc[-1]["table_stats_dict"]
    is_complex_dict = False

    if last_stats and isinstance(list(last_stats.values())[0], dict):
        is_complex_dict = True
        top_tables_by_size = sorted(
            last_stats.keys(),
            key=lambda k: last_stats[k].get("total_bytes", 0),
            reverse=True,
        )[:5]
        top_tables_by_bloat = sorted(
            last_stats.keys(),
            key=lambda k: last_stats[k].get("bloat_pct", 0),
            reverse=True,
        )[:5]
    else:
        top_tables_by_size = sorted(
            last_stats.keys(), key=lambda k: last_stats[k], reverse=True
        )[:5]
        top_tables_by_bloat = []

    # Pre-calculate GB columns
    GB = 1024**3
    df["disk_size_gb"] = df[disk_col] / GB
    df["db_size_gb"] = df[db_col] / GB

    for table in top_tables_by_size:
        if is_complex_dict:
            df[f"size_gb_{table}"] = (
                df["table_stats_dict"].apply(
                    lambda x: x.get(table, {}).get("total_bytes", 0)
                )
                / GB
            )
        else:
            df[f"size_gb_{table}"] = (
                df["table_stats_dict"].apply(lambda x: x.get(table, 0)) / GB
            )

    if is_complex_dict:
        # Guarantee top 5 largest tables and top bloated tables are tracked
        tables_to_track_bloat = list(
            dict.fromkeys(top_tables_by_bloat + top_tables_by_size)
        )
        for table in tables_to_track_bloat:
            df[f"bloat_{table}"] = df["table_stats_dict"].apply(
                lambda x: x.get(table, {}).get("bloat_pct", 0.0)
            )
            df[f"dead_{table}"] = df["table_stats_dict"].apply(
                lambda x: x.get(table, {}).get("dead_rows", 0)
            )

            # --- Vacuum Metric Calculation ---
            # 1. Parse latest vacuum timestamp series for the current table
            raw_vac_dates = df["table_stats_dict"].apply(
                lambda x: get_latest_vacuum_dt(x.get(table, {}))
            )
            # Enforce UTC timezone specifically on the Series to prevent comparison errors
            df[f"latest_vac_dt_{table}"] = pd.to_datetime(raw_vac_dates, utc=True)

            # 2. Vectorized calculation of time since vacuum in minutes
            df[f"time_since_vac_min_{table}"] = (
                df["timestamp_utc"] - df[f"latest_vac_dt_{table}"]
            ).dt.total_seconds() / 60.0

    # --- Setup Output Directory ---
    csv_stems = [os.path.splitext(os.path.basename(f))[0] for f in csv_files]
    if len(csv_stems) == 1:
        out_dir = f"pruning_dashboards_{csv_stems[0]}"
    else:
        combined = "__".join(csv_stems)
        short_hash = hashlib.md5(combined.encode()).hexdigest()[:8]
        out_dir = f"pruning_dashboards_{csv_stems[0]}_and_{len(csv_stems) - 1}_more_{short_hash}"
    os.makedirs(out_dir, exist_ok=True)
    base_name = os.path.join(out_dir, "dashboard")

    # Helper to finalize and save a figure
    def save_figure(fig, title, y_axis_title, filename):
        if pruning_start_time is not None:
            fig.add_vline(
                x=pruning_start_time, line_width=2, line_dash="dash", line_color="red"
            )
            fig.add_annotation(
                x=pruning_start_time,
                y=1.0,
                yref="paper",
                text=" Pruning Enabled",
                showarrow=False,
                font=dict(color="red"),
                xanchor="left",
                yanchor="bottom",
            )

        n_boundaries = len(csv_boundaries)
        for i, (boundary_ts, boundary_label) in enumerate(csv_boundaries):
            fig.add_vline(
                x=boundary_ts, line_width=2, line_dash="dot", line_color="yellow"
            )
            # Spread labels evenly across the full chart height
            y_pos = 0.95 - (i / max(n_boundaries, 1)) * 0.85
            fig.add_annotation(
                x=boundary_ts,
                y=y_pos,
                yref="paper",
                text=boundary_label,
                showarrow=True,
                arrowcolor="yellow",
                arrowwidth=1,
                ax=20,
                ay=0,
                font=dict(color="yellow", size=9),
                xanchor="left",
                textangle=-35,
            )

        fig.update_layout(
            title=title,
            template="plotly_dark",
            hovermode="x unified",
            yaxis_title=y_axis_title,
            legend=dict(
                orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1
            ),
        )
        fig.write_html(filename)
        print(f"  Saved: {filename}")

    print("\nGenerating separate full-screen interactive plots...")

    # 1. Overall Storage Growth
    fig_storage = go.Figure()
    fig_storage.add_trace(
        go.Scatter(
            x=df["timestamp"],
            y=df["disk_size_gb"],
            name="Physical Disk Size",
            line=dict(color="#00ff00", width=2),
        )
    )
    fig_storage.add_trace(
        go.Scatter(
            x=df["timestamp"],
            y=df["db_size_gb"],
            name="Logical DB Size",
            line=dict(color="#00aaff", width=2),
        )
    )
    save_figure(
        fig_storage,
        "Overall Storage Growth",
        "Gigabytes (GB)",
        f"{base_name}_1_storage.html",
    )

    # 2. Top 5 Largest Tables (GB)
    fig_tables = go.Figure()
    for table in top_tables_by_size:
        fig_tables.add_trace(
            go.Scatter(
                x=df["timestamp"],
                y=df[f"size_gb_{table}"],
                name=f"{table} Size",
                hovertemplate="%{y:.2f} GB",
            )
        )
    save_figure(
        fig_tables,
        "Top 5 Largest Tables",
        "Gigabytes (GB)",
        f"{base_name}_2_top_tables.html",
    )

    # 3. Ingestion Rate (TPS)
    fig_tps = go.Figure()
    fig_tps.add_trace(
        go.Scatter(
            x=df["timestamp"],
            y=df["tps"],
            name="Raw TPS",
            line=dict(color="orange", width=1),
            opacity=0.5,
        )
    )
    fig_tps.add_trace(
        go.Scatter(
            x=df["timestamp"],
            y=df["tps_smoothed"],
            name="Smoothed TPS",
            line=dict(color="red", width=2),
        )
    )
    save_figure(
        fig_tps, "Ingestion Rate (TPS)", "Transactions / sec", f"{base_name}_3_tps.html"
    )

    # 4. Epoch Progression
    if "epoch" in df.columns:
        fig_epoch = go.Figure()
        fig_epoch.add_trace(
            go.Scatter(
                x=df["timestamp"],
                y=df["epoch"],
                name="Epoch",
                line=dict(color="#ab63fa", width=2),
            )
        )
        save_figure(
            fig_epoch, "Epoch Progression", "Current Epoch", f"{base_name}_4_epoch.html"
        )

    # 5. Table Bloat (%)
    if is_complex_dict and top_tables_by_bloat:
        fig_bloat = go.Figure()
        for table in top_tables_by_bloat:
            fig_bloat.add_trace(
                go.Scatter(
                    x=df["timestamp"],
                    y=df[f"bloat_{table}"],
                    name=f"{table} Bloat",
                    hovertemplate="%{y:.2f}%",
                )
            )
        fig_bloat.update_yaxes(range=[0, 105])
        save_figure(
            fig_bloat,
            "Table Bloat (% of Space Wasted)",
            "Bloat (%)",
            f"{base_name}_5_bloat.html",
        )

    # 6. Dead Rows Count
    if is_complex_dict:
        fig_dead = go.Figure()

        # Limit strictly to the top 5 largest tables
        for table in top_tables_by_size:
            if f"dead_{table}" in df.columns:
                fig_dead.add_trace(
                    go.Scatter(
                        x=df["timestamp"],
                        y=df[f"dead_{table}"],
                        name=f"{table} Dead Rows",
                    )
                )

        save_figure(
            fig_dead,
            "Dead Rows",
            "Dead Row Count",
            f"{base_name}_6_dead_rows.html",
        )

    # 7. Pruning Progress (%)
    if pruning_col in df.columns:
        fig_pruning = go.Figure()
        tracked_entities = ["transactions", "tx_digests", "checkpoints"]
        for entity in tracked_entities:
            pct_list = []
            for row_list in df["pruning_list"]:
                val = 0.0
                for item in row_list:
                    if item.get("entity") == entity:
                        val = item.get("pct_total", 0.0)
                        break
                pct_list.append(val)
            fig_pruning.add_trace(
                go.Scatter(
                    x=df["timestamp"],
                    y=pct_list,
                    name=f"{entity} Pruned",
                    hovertemplate="%{y:.2f}%",
                )
            )
        fig_pruning.update_yaxes(range=[-5, 105])
        save_figure(
            fig_pruning,
            "Watermark Pruning Progress",
            "Pruned (%)",
            f"{base_name}_7_pruning.html",
        )

    # 8. Time Since Last Vacuum (Auto or Manual)
    if is_complex_dict:
        fig_vac = go.Figure()

        for table in tables_to_track_bloat:
            col_name = f"time_since_vac_min_{table}"
            if col_name in df.columns:
                # Add trace only if there's at least one non-NaN value (i.e. table was vacuumed)
                if not df[col_name].isna().all():
                    fig_vac.add_trace(
                        go.Scatter(
                            x=df["timestamp"],
                            y=df[col_name],
                            name=f"{table} Vacuum Age",
                            hovertemplate="%{y:.1f} mins",
                        )
                    )

        save_figure(
            fig_vac,
            "Table Vacuum Age",
            "Minutes Since Last Vacuum",
            f"{base_name}_8_vacuum_time.html",
        )

    print("\n✅ All full-screen dashboards generated successfully!")


if __name__ == "__main__":
    main()
