[package]
name = "authenticator_inputs_cryptographic_protection"
edition = "2024"

[dependencies]
Iota = { local = "../../../../../crates/iota-framework/packages/iota-framework" }

[addresses]
authenticator_inputs_cryptographic_protection = "0x0"
