-- Revert custom autovacuum and index cleanup settings back to default
ALTER TABLE checkpoints RESET (vacuum_index_cleanup, autovacuum_vacuum_scale_factor, autovacuum_vacuum_cost_limit, autovacuum_vacuum_cost_delay, autovacuum_enabled);
ALTER TABLE pruner_cp_watermark RESET (vacuum_index_cleanup, autovacuum_vacuum_scale_factor, autovacuum_vacuum_cost_limit, autovacuum_vacuum_cost_delay, autovacuum_enabled);

ALTER TABLE event_emit_package RESET (vacuum_index_cleanup, autovacuum_vacuum_scale_factor, autovacuum_vacuum_cost_limit, autovacuum_vacuum_cost_delay, autovacuum_enabled);
ALTER TABLE event_emit_module RESET (vacuum_index_cleanup, autovacuum_vacuum_scale_factor, autovacuum_vacuum_cost_limit, autovacuum_vacuum_cost_delay, autovacuum_enabled);
ALTER TABLE event_senders RESET (vacuum_index_cleanup, autovacuum_vacuum_scale_factor, autovacuum_vacuum_cost_limit, autovacuum_vacuum_cost_delay, autovacuum_enabled);
ALTER TABLE event_struct_instantiation RESET (vacuum_index_cleanup, autovacuum_vacuum_scale_factor, autovacuum_vacuum_cost_limit, autovacuum_vacuum_cost_delay, autovacuum_enabled);
ALTER TABLE event_struct_module RESET (vacuum_index_cleanup, autovacuum_vacuum_scale_factor, autovacuum_vacuum_cost_limit, autovacuum_vacuum_cost_delay, autovacuum_enabled);
ALTER TABLE event_struct_name RESET (vacuum_index_cleanup, autovacuum_vacuum_scale_factor, autovacuum_vacuum_cost_limit, autovacuum_vacuum_cost_delay, autovacuum_enabled);
ALTER TABLE event_struct_package RESET (vacuum_index_cleanup, autovacuum_vacuum_scale_factor, autovacuum_vacuum_cost_limit, autovacuum_vacuum_cost_delay, autovacuum_enabled);

ALTER TABLE tx_calls_pkg RESET (vacuum_index_cleanup, autovacuum_vacuum_scale_factor, autovacuum_vacuum_cost_limit, autovacuum_vacuum_cost_delay, autovacuum_enabled);
ALTER TABLE tx_calls_mod RESET (vacuum_index_cleanup, autovacuum_vacuum_scale_factor, autovacuum_vacuum_cost_limit, autovacuum_vacuum_cost_delay, autovacuum_enabled);
ALTER TABLE tx_calls_fun RESET (vacuum_index_cleanup, autovacuum_vacuum_scale_factor, autovacuum_vacuum_cost_limit, autovacuum_vacuum_cost_delay, autovacuum_enabled);
ALTER TABLE tx_changed_objects RESET (vacuum_index_cleanup, autovacuum_vacuum_scale_factor, autovacuum_vacuum_cost_limit, autovacuum_vacuum_cost_delay, autovacuum_enabled);
ALTER TABLE tx_digests RESET (vacuum_index_cleanup, autovacuum_vacuum_scale_factor, autovacuum_vacuum_cost_limit, autovacuum_vacuum_cost_delay, autovacuum_enabled);
ALTER TABLE tx_input_objects RESET (vacuum_index_cleanup, autovacuum_vacuum_scale_factor, autovacuum_vacuum_cost_limit, autovacuum_vacuum_cost_delay, autovacuum_enabled);
ALTER TABLE tx_kinds RESET (vacuum_index_cleanup, autovacuum_vacuum_scale_factor, autovacuum_vacuum_cost_limit, autovacuum_vacuum_cost_delay, autovacuum_enabled);
ALTER TABLE tx_recipients RESET (vacuum_index_cleanup, autovacuum_vacuum_scale_factor, autovacuum_vacuum_cost_limit, autovacuum_vacuum_cost_delay, autovacuum_enabled);
ALTER TABLE tx_senders RESET (vacuum_index_cleanup, autovacuum_vacuum_scale_factor, autovacuum_vacuum_cost_limit, autovacuum_vacuum_cost_delay, autovacuum_enabled);
ALTER TABLE tx_wrapped_or_deleted_objects RESET (vacuum_index_cleanup, autovacuum_vacuum_scale_factor, autovacuum_vacuum_cost_limit, autovacuum_vacuum_cost_delay, autovacuum_enabled);
ALTER TABLE tx_global_order RESET (vacuum_index_cleanup, autovacuum_vacuum_scale_factor, autovacuum_vacuum_cost_limit, autovacuum_vacuum_cost_delay, autovacuum_enabled);

ALTER TABLE optimistic_transactions RESET (vacuum_index_cleanup, autovacuum_vacuum_scale_factor, autovacuum_vacuum_cost_limit, autovacuum_vacuum_cost_delay, autovacuum_enabled);
