[package]
name = "dag-visualizer-server"
version = "0.1.0"
authors = ["IOTA Foundation <info@iota.org>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = "A backend service providing historical and real-time data to the dag-visualizer frontend"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(msim)', 'cfg(fail_points)'] }

[dependencies]
# external dependencies
axum = { version = "0.8", default-features = false, features = ["tokio", "http1", "http2", "query", "ws", "macros"] }
bcs = "0.1.4"
clap = { version = "4.4", features = ["derive", "wrap_help"] }
hex = "0.4.3"
http = "1"
parking_lot = { version = "0.12.3", features = ["arc_lock"] }
prost = "0.14"
serde = { version = "1.0.144", features = ["derive", "rc"] }
tokio = { version = "1.49.0", features = ["full"] }
tokio-stream = { version = "0.1.17", features = ["sync", "net"] }
tonic = { version = "0.14", features = ["zstd", "transport"] }
tower-http = { version = "0.5", features = ["cors"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", default-features = false, features = ["std", "smallvec", "fmt", "ansi", "time", "json", "registry", "env-filter"] }

# internal dependencies
dag-visualizer-proto = { path = "../../../crates/starfish/dag-visualizer-proto" }
typed-store = { path = "../../../crates/typed-store" }

[dev-dependencies]
tempfile = "3.20.0"

[workspace]
