name: Hierarchy

on:
  push:
    branches:
      - "develop"
      - "devnet"
      - "testnet"
      - "mainnet"
      - "releases/iota-*-release"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  diff:
    runs-on: [ubuntu-latest]
    concurrency:
      group: diff-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}
    if: (github.event.pull_request.draft == false || contains(github.event.pull_request.body, '[run-ci]'))
    outputs:
      isRust: ${{ steps.diff.outputs.isRust }}
      isRustWorkspaceConfig: ${{ steps.diff.outputs.isRustWorkspaceConfig }}
      isRustExample: ${{ steps.diff.outputs.isRustExample }}
      isRpc: ${{ steps.diff.outputs.isRpc }}
      isPgIntegration: ${{ steps.diff.outputs.isPgIntegration }}
      isMoveExampleUsedByOthers: ${{ steps.diff.outputs.isMoveExampleUsedByOthers }}
      isDoc: ${{ steps.diff.outputs.isDoc }}
      isReleaseNotesEligible: ${{ steps.diff.outputs.isReleaseNotesEligible }}
      isExternalCrates: ${{ steps.diff.outputs.isExternalCrates }}
      isStarfishSynchronization: ${{ steps.diff.outputs.isStarfishSynchronization }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Detect Changes (diff)
        uses: "./.github/actions/diffs"
        id: diff

  release-notes-check:
    concurrency:
      group: release-notes-check-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}
    if: github.event_name == 'pull_request'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: |
          cd scripts/release_notes
          ./run.sh check-pr ${{ github.event.pull_request.number }}

  dprint-format:
    runs-on: [self-hosted-x64]
    concurrency:
      group: dprint-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}
    if: (github.event.pull_request.draft == false || contains(github.event.pull_request.body, '[run-ci]'))
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Check dprint formatting
        run: dprint check

  typos:
    if: (github.event.pull_request.draft == false || contains(github.event.pull_request.body, '[run-ci]'))
    uses: ./.github/workflows/_typos.yml

  license-check:
    name: license-check
    concurrency:
      group: license-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}
    needs: diff
    if: (!cancelled() && !failure() && needs.diff.outputs.isRust == 'true' && (github.event.pull_request.draft == false || contains(github.event.pull_request.body, '[run-ci]')))
    runs-on: [self-hosted-x64]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run license check
        run: cargo ci-license

  docusaurus:
    needs: diff
    if: (!cancelled() && !failure() && needs.diff.outputs.isDoc == 'true' && (github.event.pull_request.draft == false || contains(github.event.pull_request.body, '[run-ci]')))
    uses: ./.github/workflows/_docusaurus.yml

  docs-lint:
    needs: diff
    if: (!cancelled() && !failure() && needs.diff.outputs.isDoc == 'true' && (github.event.pull_request.draft == false || contains(github.event.pull_request.body, '[run-ci]')))
    uses: ./.github/workflows/_docs_lint.yml

  rust:
    needs:
      - diff
      - dprint-format
      - license-check
      - typos
    if: (!cancelled() && !failure() && (github.event.pull_request.draft == false || contains(github.event.pull_request.body, '[run-ci]')))
    uses: ./.github/workflows/_rust.yml
    secrets: inherit
    with:
      isRust: ${{ needs.diff.outputs.isRust == 'true' }}
      isRustWorkspaceConfig: ${{ needs.diff.outputs.isRustWorkspaceConfig == 'true' }}
      isRustExample: ${{ needs.diff.outputs.isRustExample == 'true' }}
      isPgIntegration: ${{ needs.diff.outputs.isPgIntegration == 'true' }}
      isMoveExampleUsedByOthers: ${{ needs.diff.outputs.isMoveExampleUsedByOthers == 'true' }}

  move-ide:
    needs:
      - diff
      - dprint-format
      - license-check
      - typos
    if: (!cancelled() && !failure() && needs.diff.outputs.isExternalCrates == 'true' && (github.event.pull_request.draft == false || contains(github.event.pull_request.body, '[run-ci]')))
    uses: ./.github/workflows/_move_ide.yml

  split-cluster:
    needs:
      - diff
      - dprint-format
      - license-check
      - typos
      - rust
    if: (!cancelled() && !failure() && needs.diff.outputs.isRust == 'true' && (github.event.pull_request.draft == false || contains(github.event.pull_request.body, '[run-ci]')))
    uses: ./.github/workflows/_split_cluster.yml

  split-cluster-sync-check:
    needs:
      - diff
      - rust
    if: (!cancelled() && !failure() && needs.diff.outputs.isStarfishSynchronization == 'true' && (github.event.pull_request.draft == false || contains(github.event.pull_request.body, '[run-ci]')))
    uses: ./.github/workflows/_split_cluster_sync_check.yml
